TonAPI:
  TonConfig: "tonlib.config.json.example"
  DiceAddress: "kQBgMySA9l-X185xzrEm20M0INDbi0AavYOog9p0133yq-ZJ"
  GetBetMethodID: 110679
  LiteClient: "bin/lite-client"
  LiteClientConfig: "ton-lite-client-test1.config.json"
