// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FetchTransactionsRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Lt                   int64    `protobuf:"varint,2,opt,name=lt,proto3" json:"lt,omitempty"`
	Hash                 string   `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchTransactionsRequest) Reset()         { *m = FetchTransactionsRequest{} }
func (m *FetchTransactionsRequest) String() string { return proto.CompactTextString(m) }
func (*FetchTransactionsRequest) ProtoMessage()    {}
func (*FetchTransactionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *FetchTransactionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchTransactionsRequest.Unmarshal(m, b)
}
func (m *FetchTransactionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchTransactionsRequest.Marshal(b, m, deterministic)
}
func (m *FetchTransactionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchTransactionsRequest.Merge(m, src)
}
func (m *FetchTransactionsRequest) XXX_Size() int {
	return xxx_messageInfo_FetchTransactionsRequest.Size(m)
}
func (m *FetchTransactionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchTransactionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchTransactionsRequest proto.InternalMessageInfo

func (m *FetchTransactionsRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *FetchTransactionsRequest) GetLt() int64 {
	if m != nil {
		return m.Lt
	}
	return 0
}

func (m *FetchTransactionsRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type FetchTransactionsResponse struct {
	Items                []*Transaction `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *FetchTransactionsResponse) Reset()         { *m = FetchTransactionsResponse{} }
func (m *FetchTransactionsResponse) String() string { return proto.CompactTextString(m) }
func (*FetchTransactionsResponse) ProtoMessage()    {}
func (*FetchTransactionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *FetchTransactionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchTransactionsResponse.Unmarshal(m, b)
}
func (m *FetchTransactionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchTransactionsResponse.Marshal(b, m, deterministic)
}
func (m *FetchTransactionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchTransactionsResponse.Merge(m, src)
}
func (m *FetchTransactionsResponse) XXX_Size() int {
	return xxx_messageInfo_FetchTransactionsResponse.Size(m)
}
func (m *FetchTransactionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchTransactionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchTransactionsResponse proto.InternalMessageInfo

func (m *FetchTransactionsResponse) GetItems() []*Transaction {
	if m != nil {
		return m.Items
	}
	return nil
}

type Transaction struct {
	Data                 string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Fee                  int64                  `protobuf:"varint,2,opt,name=fee,proto3" json:"fee,omitempty"`
	InMsg                *RawMessage            `protobuf:"bytes,3,opt,name=in_msg,json=inMsg,proto3" json:"in_msg,omitempty"`
	OtherFee             int64                  `protobuf:"varint,4,opt,name=other_fee,json=otherFee,proto3" json:"other_fee,omitempty"`
	OutMsgs              []*RawMessage          `protobuf:"bytes,5,rep,name=out_msgs,json=outMsgs,proto3" json:"out_msgs,omitempty"`
	StorageFee           int64                  `protobuf:"varint,6,opt,name=storage_fee,json=storageFee,proto3" json:"storage_fee,omitempty"`
	TransactionId        *InternalTransactionId `protobuf:"bytes,7,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Transaction) GetFee() int64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *Transaction) GetInMsg() *RawMessage {
	if m != nil {
		return m.InMsg
	}
	return nil
}

func (m *Transaction) GetOtherFee() int64 {
	if m != nil {
		return m.OtherFee
	}
	return 0
}

func (m *Transaction) GetOutMsgs() []*RawMessage {
	if m != nil {
		return m.OutMsgs
	}
	return nil
}

func (m *Transaction) GetStorageFee() int64 {
	if m != nil {
		return m.StorageFee
	}
	return 0
}

func (m *Transaction) GetTransactionId() *InternalTransactionId {
	if m != nil {
		return m.TransactionId
	}
	return nil
}

type RawMessage struct {
	BodyHash             string   `protobuf:"bytes,1,opt,name=body_hash,json=bodyHash,proto3" json:"body_hash,omitempty"`
	CreatedLt            int64    `protobuf:"varint,2,opt,name=created_lt,json=createdLt,proto3" json:"created_lt,omitempty"`
	Destination          string   `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	FwdFee               int64    `protobuf:"varint,4,opt,name=fwd_fee,json=fwdFee,proto3" json:"fwd_fee,omitempty"`
	IhrFee               int64    `protobuf:"varint,5,opt,name=ihr_fee,json=ihrFee,proto3" json:"ihr_fee,omitempty"`
	Message              string   `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	Source               string   `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	Value                int64    `protobuf:"varint,8,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawMessage) Reset()         { *m = RawMessage{} }
func (m *RawMessage) String() string { return proto.CompactTextString(m) }
func (*RawMessage) ProtoMessage()    {}
func (*RawMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *RawMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawMessage.Unmarshal(m, b)
}
func (m *RawMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawMessage.Marshal(b, m, deterministic)
}
func (m *RawMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawMessage.Merge(m, src)
}
func (m *RawMessage) XXX_Size() int {
	return xxx_messageInfo_RawMessage.Size(m)
}
func (m *RawMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_RawMessage.DiscardUnknown(m)
}

var xxx_messageInfo_RawMessage proto.InternalMessageInfo

func (m *RawMessage) GetBodyHash() string {
	if m != nil {
		return m.BodyHash
	}
	return ""
}

func (m *RawMessage) GetCreatedLt() int64 {
	if m != nil {
		return m.CreatedLt
	}
	return 0
}

func (m *RawMessage) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *RawMessage) GetFwdFee() int64 {
	if m != nil {
		return m.FwdFee
	}
	return 0
}

func (m *RawMessage) GetIhrFee() int64 {
	if m != nil {
		return m.IhrFee
	}
	return 0
}

func (m *RawMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RawMessage) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *RawMessage) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type InternalTransactionId struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Lt                   int64    `protobuf:"varint,2,opt,name=lt,proto3" json:"lt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InternalTransactionId) Reset()         { *m = InternalTransactionId{} }
func (m *InternalTransactionId) String() string { return proto.CompactTextString(m) }
func (*InternalTransactionId) ProtoMessage()    {}
func (*InternalTransactionId) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *InternalTransactionId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InternalTransactionId.Unmarshal(m, b)
}
func (m *InternalTransactionId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InternalTransactionId.Marshal(b, m, deterministic)
}
func (m *InternalTransactionId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InternalTransactionId.Merge(m, src)
}
func (m *InternalTransactionId) XXX_Size() int {
	return xxx_messageInfo_InternalTransactionId.Size(m)
}
func (m *InternalTransactionId) XXX_DiscardUnknown() {
	xxx_messageInfo_InternalTransactionId.DiscardUnknown(m)
}

var xxx_messageInfo_InternalTransactionId proto.InternalMessageInfo

func (m *InternalTransactionId) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *InternalTransactionId) GetLt() int64 {
	if m != nil {
		return m.Lt
	}
	return 0
}

type GetAccountStateRequest struct {
	AccountAddress       string   `protobuf:"bytes,1,opt,name=account_address,json=accountAddress,proto3" json:"account_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountStateRequest) Reset()         { *m = GetAccountStateRequest{} }
func (m *GetAccountStateRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountStateRequest) ProtoMessage()    {}
func (*GetAccountStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *GetAccountStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountStateRequest.Unmarshal(m, b)
}
func (m *GetAccountStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountStateRequest.Marshal(b, m, deterministic)
}
func (m *GetAccountStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountStateRequest.Merge(m, src)
}
func (m *GetAccountStateRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountStateRequest.Size(m)
}
func (m *GetAccountStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountStateRequest proto.InternalMessageInfo

func (m *GetAccountStateRequest) GetAccountAddress() string {
	if m != nil {
		return m.AccountAddress
	}
	return ""
}

type GetAccountStateResponse struct {
	Balance              int64                  `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Code                 string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Data                 string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	FrozenHash           string                 `protobuf:"bytes,4,opt,name=frozen_hash,json=frozenHash,proto3" json:"frozen_hash,omitempty"`
	LastTransactionId    *InternalTransactionId `protobuf:"bytes,5,opt,name=last_transaction_id,json=lastTransactionId,proto3" json:"last_transaction_id,omitempty"`
	SyncUtime            int64                  `protobuf:"varint,6,opt,name=sync_utime,json=syncUtime,proto3" json:"sync_utime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetAccountStateResponse) Reset()         { *m = GetAccountStateResponse{} }
func (m *GetAccountStateResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccountStateResponse) ProtoMessage()    {}
func (*GetAccountStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *GetAccountStateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountStateResponse.Unmarshal(m, b)
}
func (m *GetAccountStateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountStateResponse.Marshal(b, m, deterministic)
}
func (m *GetAccountStateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountStateResponse.Merge(m, src)
}
func (m *GetAccountStateResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccountStateResponse.Size(m)
}
func (m *GetAccountStateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountStateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountStateResponse proto.InternalMessageInfo

func (m *GetAccountStateResponse) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *GetAccountStateResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *GetAccountStateResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *GetAccountStateResponse) GetFrozenHash() string {
	if m != nil {
		return m.FrozenHash
	}
	return ""
}

func (m *GetAccountStateResponse) GetLastTransactionId() *InternalTransactionId {
	if m != nil {
		return m.LastTransactionId
	}
	return nil
}

func (m *GetAccountStateResponse) GetSyncUtime() int64 {
	if m != nil {
		return m.SyncUtime
	}
	return 0
}

type GetBetSeedRequest struct {
	BetId                int64    `protobuf:"varint,1,opt,name=bet_id,json=betId,proto3" json:"bet_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBetSeedRequest) Reset()         { *m = GetBetSeedRequest{} }
func (m *GetBetSeedRequest) String() string { return proto.CompactTextString(m) }
func (*GetBetSeedRequest) ProtoMessage()    {}
func (*GetBetSeedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *GetBetSeedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBetSeedRequest.Unmarshal(m, b)
}
func (m *GetBetSeedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBetSeedRequest.Marshal(b, m, deterministic)
}
func (m *GetBetSeedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBetSeedRequest.Merge(m, src)
}
func (m *GetBetSeedRequest) XXX_Size() int {
	return xxx_messageInfo_GetBetSeedRequest.Size(m)
}
func (m *GetBetSeedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBetSeedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBetSeedRequest proto.InternalMessageInfo

func (m *GetBetSeedRequest) GetBetId() int64 {
	if m != nil {
		return m.BetId
	}
	return 0
}

type GetBetSeedResponse struct {
	Seed                 string   `protobuf:"bytes,1,opt,name=seed,proto3" json:"seed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBetSeedResponse) Reset()         { *m = GetBetSeedResponse{} }
func (m *GetBetSeedResponse) String() string { return proto.CompactTextString(m) }
func (*GetBetSeedResponse) ProtoMessage()    {}
func (*GetBetSeedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}

func (m *GetBetSeedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBetSeedResponse.Unmarshal(m, b)
}
func (m *GetBetSeedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBetSeedResponse.Marshal(b, m, deterministic)
}
func (m *GetBetSeedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBetSeedResponse.Merge(m, src)
}
func (m *GetBetSeedResponse) XXX_Size() int {
	return xxx_messageInfo_GetBetSeedResponse.Size(m)
}
func (m *GetBetSeedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBetSeedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBetSeedResponse proto.InternalMessageInfo

func (m *GetBetSeedResponse) GetSeed() string {
	if m != nil {
		return m.Seed
	}
	return ""
}

func init() {
	proto.RegisterType((*FetchTransactionsRequest)(nil), "api.FetchTransactionsRequest")
	proto.RegisterType((*FetchTransactionsResponse)(nil), "api.FetchTransactionsResponse")
	proto.RegisterType((*Transaction)(nil), "api.Transaction")
	proto.RegisterType((*RawMessage)(nil), "api.RawMessage")
	proto.RegisterType((*InternalTransactionId)(nil), "api.InternalTransactionId")
	proto.RegisterType((*GetAccountStateRequest)(nil), "api.GetAccountStateRequest")
	proto.RegisterType((*GetAccountStateResponse)(nil), "api.GetAccountStateResponse")
	proto.RegisterType((*GetBetSeedRequest)(nil), "api.GetBetSeedRequest")
	proto.RegisterType((*GetBetSeedResponse)(nil), "api.GetBetSeedResponse")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 652 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xcf, 0x6f, 0xd3, 0x4a,
	0x10, 0x7e, 0x89, 0x63, 0x3b, 0x9e, 0xe8, 0xf5, 0xc7, 0xbe, 0xd7, 0xc6, 0xa4, 0x94, 0x56, 0x3e,
	0x94, 0xa8, 0x87, 0x1e, 0xca, 0x91, 0x03, 0x0a, 0x48, 0x2d, 0x45, 0x94, 0x83, 0x5b, 0x24, 0x6e,
	0xd6, 0xc6, 0x3b, 0x89, 0x2d, 0x25, 0xde, 0xe0, 0x1d, 0x53, 0x95, 0xbf, 0x80, 0x3f, 0x14, 0x89,
	0x23, 0xff, 0x02, 0xda, 0xb5, 0x9d, 0xb8, 0x4d, 0x2a, 0x6e, 0x3b, 0xdf, 0xec, 0x7c, 0x3b, 0xf3,
	0xcd, 0xa7, 0x05, 0x8f, 0x2f, 0xd2, 0xb3, 0x45, 0x2e, 0x49, 0x32, 0x8b, 0x2f, 0xd2, 0xe0, 0x0b,
	0xf8, 0x17, 0x48, 0x71, 0x72, 0x9b, 0xf3, 0x4c, 0xf1, 0x98, 0x52, 0x99, 0xa9, 0x10, 0xbf, 0x16,
	0xa8, 0x88, 0xf9, 0xe0, 0x72, 0x21, 0x72, 0x54, 0xca, 0x6f, 0x1d, 0xb7, 0x86, 0x5e, 0x58, 0x87,
	0x6c, 0x0b, 0xda, 0x33, 0xf2, 0xdb, 0xc7, 0xad, 0xa1, 0x15, 0xb6, 0x67, 0xc4, 0x18, 0x74, 0x12,
	0xae, 0x12, 0xdf, 0x32, 0xd7, 0xcc, 0x39, 0x78, 0x07, 0xcf, 0x36, 0x30, 0xab, 0x85, 0xcc, 0x14,
	0xb2, 0x13, 0xb0, 0x53, 0xc2, 0xb9, 0x26, 0xb6, 0x86, 0xbd, 0xf3, 0x9d, 0x33, 0xdd, 0x56, 0xe3,
	0x66, 0x58, 0xa6, 0x83, 0x1f, 0x6d, 0xe8, 0x35, 0x60, 0xfd, 0x90, 0xe0, 0xc4, 0xab, 0x7e, 0xcc,
	0x99, 0xed, 0x80, 0x35, 0x41, 0xac, 0xba, 0xd1, 0x47, 0x76, 0x02, 0x4e, 0x9a, 0x45, 0x73, 0x35,
	0x35, 0x0d, 0xf5, 0xce, 0xb7, 0x0d, 0x7d, 0xc8, 0xef, 0xae, 0x51, 0x29, 0x3e, 0xc5, 0xd0, 0x4e,
	0xb3, 0x6b, 0x35, 0x65, 0x07, 0xe0, 0x49, 0x4a, 0x30, 0x8f, 0x74, 0x7d, 0xc7, 0xd4, 0x77, 0x0d,
	0x70, 0x81, 0xc8, 0x4e, 0xa1, 0x2b, 0x0b, 0xd2, 0x2c, 0xca, 0xb7, 0x4d, 0x97, 0x6b, 0x34, 0xae,
	0x2c, 0xe8, 0x5a, 0x4d, 0x15, 0x3b, 0x82, 0x9e, 0x22, 0x99, 0xf3, 0x29, 0x1a, 0x2a, 0xc7, 0x50,
	0x41, 0x05, 0x69, 0xb2, 0x11, 0x6c, 0xd1, 0x6a, 0x8c, 0x28, 0x15, 0xbe, 0x6b, 0x3a, 0x1b, 0x18,
	0xca, 0xab, 0x8c, 0x30, 0xcf, 0xf8, 0xac, 0x31, 0xe9, 0x95, 0x08, 0xff, 0xa5, 0x66, 0x18, 0xfc,
	0x6c, 0x01, 0xac, 0xde, 0xd6, 0xbd, 0x8f, 0xa5, 0xb8, 0x8f, 0x8c, 0xee, 0xa5, 0x1c, 0x5d, 0x0d,
	0xbc, 0xe7, 0x2a, 0x61, 0x87, 0x00, 0x71, 0x8e, 0x9c, 0x50, 0x44, 0xcb, 0x3d, 0x79, 0x15, 0xf2,
	0x91, 0xd8, 0x31, 0xf4, 0x04, 0x2a, 0x4a, 0x33, 0xae, 0xb9, 0xab, 0xad, 0x35, 0x21, 0xd6, 0x07,
	0x77, 0x72, 0x27, 0x1a, 0xba, 0x38, 0x93, 0x3b, 0xa1, 0x07, 0xe9, 0x83, 0x9b, 0x26, 0xa5, 0x60,
	0x76, 0x99, 0x48, 0x13, 0x23, 0x97, 0x0f, 0xee, 0xbc, 0x6c, 0xcd, 0x8c, 0xef, 0x85, 0x75, 0xc8,
	0xf6, 0xc1, 0x51, 0xb2, 0xc8, 0x63, 0x34, 0x33, 0x7b, 0x61, 0x15, 0xb1, 0xff, 0xc1, 0xfe, 0xc6,
	0x67, 0x05, 0xfa, 0x5d, 0x43, 0x54, 0x06, 0xc1, 0x6b, 0xd8, 0xdb, 0x28, 0xc7, 0xd2, 0x63, 0xad,
	0x95, 0xc7, 0x1e, 0xfb, 0x30, 0x18, 0xc1, 0xfe, 0x25, 0xd2, 0x28, 0x8e, 0x65, 0x91, 0xd1, 0x0d,
	0x71, 0xc2, 0xda, 0xcb, 0x2f, 0x61, 0x9b, 0x97, 0x70, 0xf4, 0xd0, 0xd3, 0x5b, 0x15, 0x3c, 0x2a,
	0xd1, 0xe0, 0x57, 0x0b, 0xfa, 0x6b, 0x1c, 0x95, 0x6b, 0x7d, 0x70, 0xc7, 0x7c, 0xc6, 0xb3, 0x18,
	0x4d, 0xb1, 0x15, 0xd6, 0xa1, 0x6e, 0x2e, 0x96, 0xa2, 0x34, 0xa1, 0x17, 0x9a, 0xf3, 0xd2, 0xab,
	0x56, 0xc3, 0xab, 0x47, 0xd0, 0x9b, 0xe4, 0xf2, 0x3b, 0x66, 0xe5, 0xde, 0x3a, 0x26, 0x05, 0x25,
	0x64, 0x36, 0xf7, 0x01, 0xfe, 0x9b, 0x71, 0x45, 0xd1, 0x23, 0xb7, 0xd8, 0x7f, 0x75, 0xcb, 0xae,
	0x2e, 0x7b, 0xa8, 0xd8, 0x21, 0x80, 0xba, 0xcf, 0xe2, 0xa8, 0xa0, 0x74, 0x5e, 0x9b, 0xd2, 0xd3,
	0xc8, 0x67, 0x0d, 0x04, 0xa7, 0xb0, 0x7b, 0x89, 0xf4, 0x16, 0xe9, 0x06, 0x51, 0xd4, 0x3a, 0xed,
	0x81, 0x33, 0x46, 0xd2, 0x4f, 0x96, 0x13, 0xda, 0x63, 0xa4, 0x2b, 0x11, 0x0c, 0x81, 0x35, 0xef,
	0x56, 0x7a, 0x30, 0xe8, 0x28, 0x44, 0x51, 0xaf, 0x44, 0x9f, 0xcf, 0x7f, 0xb7, 0xc0, 0xb9, 0x95,
	0xd9, 0x68, 0x91, 0xb2, 0x5b, 0xd8, 0x5d, 0xfb, 0x01, 0xd8, 0xa1, 0x99, 0xe1, 0xa9, 0x3f, 0x67,
	0xf0, 0xe2, 0xa9, 0x74, 0xf9, 0x64, 0xf0, 0x0f, 0xfb, 0x04, 0xdb, 0x8f, 0xf6, 0xc3, 0x0e, 0x4c,
	0xd1, 0xe6, 0xcd, 0x0f, 0x9e, 0x6f, 0x4e, 0x2e, 0xf9, 0xde, 0x00, 0xac, 0x46, 0x63, 0xfb, 0xf5,
	0xed, 0x87, 0xba, 0x0c, 0xfa, 0x6b, 0x78, 0x4d, 0x30, 0x76, 0xcc, 0x77, 0xfa, 0xea, 0x4f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x94, 0x96, 0x4c, 0xb9, 0x5b, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TonApiClient is the client API for TonApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TonApiClient interface {
	FetchTransactions(ctx context.Context, in *FetchTransactionsRequest, opts ...grpc.CallOption) (*FetchTransactionsResponse, error)
	GetAccountState(ctx context.Context, in *GetAccountStateRequest, opts ...grpc.CallOption) (*GetAccountStateResponse, error)
	// rpc RunGetMethod (RunGetMethodRequest) returns (RunGetMethodResponse) {}
	GetBetSeed(ctx context.Context, in *GetBetSeedRequest, opts ...grpc.CallOption) (*GetBetSeedResponse, error)
}

type tonApiClient struct {
	cc grpc.ClientConnInterface
}

func NewTonApiClient(cc grpc.ClientConnInterface) TonApiClient {
	return &tonApiClient{cc}
}

func (c *tonApiClient) FetchTransactions(ctx context.Context, in *FetchTransactionsRequest, opts ...grpc.CallOption) (*FetchTransactionsResponse, error) {
	out := new(FetchTransactionsResponse)
	err := c.cc.Invoke(ctx, "/api.TonApi/FetchTransactions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tonApiClient) GetAccountState(ctx context.Context, in *GetAccountStateRequest, opts ...grpc.CallOption) (*GetAccountStateResponse, error) {
	out := new(GetAccountStateResponse)
	err := c.cc.Invoke(ctx, "/api.TonApi/GetAccountState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tonApiClient) GetBetSeed(ctx context.Context, in *GetBetSeedRequest, opts ...grpc.CallOption) (*GetBetSeedResponse, error) {
	out := new(GetBetSeedResponse)
	err := c.cc.Invoke(ctx, "/api.TonApi/GetBetSeed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TonApiServer is the server API for TonApi service.
type TonApiServer interface {
	FetchTransactions(context.Context, *FetchTransactionsRequest) (*FetchTransactionsResponse, error)
	GetAccountState(context.Context, *GetAccountStateRequest) (*GetAccountStateResponse, error)
	// rpc RunGetMethod (RunGetMethodRequest) returns (RunGetMethodResponse) {}
	GetBetSeed(context.Context, *GetBetSeedRequest) (*GetBetSeedResponse, error)
}

// UnimplementedTonApiServer can be embedded to have forward compatible implementations.
type UnimplementedTonApiServer struct {
}

func (*UnimplementedTonApiServer) FetchTransactions(ctx context.Context, req *FetchTransactionsRequest) (*FetchTransactionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchTransactions not implemented")
}
func (*UnimplementedTonApiServer) GetAccountState(ctx context.Context, req *GetAccountStateRequest) (*GetAccountStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountState not implemented")
}
func (*UnimplementedTonApiServer) GetBetSeed(ctx context.Context, req *GetBetSeedRequest) (*GetBetSeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBetSeed not implemented")
}

func RegisterTonApiServer(s *grpc.Server, srv TonApiServer) {
	s.RegisterService(&_TonApi_serviceDesc, srv)
}

func _TonApi_FetchTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TonApiServer).FetchTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TonApi/FetchTransactions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TonApiServer).FetchTransactions(ctx, req.(*FetchTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TonApi_GetAccountState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TonApiServer).GetAccountState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TonApi/GetAccountState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TonApiServer).GetAccountState(ctx, req.(*GetAccountStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TonApi_GetBetSeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBetSeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TonApiServer).GetBetSeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TonApi/GetBetSeed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TonApiServer).GetBetSeed(ctx, req.(*GetBetSeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TonApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.TonApi",
	HandlerType: (*TonApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchTransactions",
			Handler:    _TonApi_FetchTransactions_Handler,
		},
		{
			MethodName: "GetAccountState",
			Handler:    _TonApi_GetAccountState_Handler,
		},
		{
			MethodName: "GetBetSeed",
			Handler:    _TonApi_GetBetSeed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
